[package]
name = "sensor_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
data_transfer_objects = { path = "../data_transfer_objects" }
postcard = "1.0.2"
serde = { version = "1.0", default-features = false }
env_logger = "0.10.0"
log = "0.4.19"