repetitions = 3
motor_groups_tcp = [1]
durations = [10]
window_size_ms = [1000]
window_sampling_interval_ms = [500]
sensor_sampling_interval_ms = [5]
thread_pool_sizes = [80]
request_processing_models = ["SpringQL", "ReactiveStreaming"]
