repetitions = 10
motor_groups_tcp = [1, 2, 4, 8, 16, 32, 59]
durations = [60]
window_size_seconds = [1]
sampling_interval_ms = [1000]
thread_pool_sizes = [200]
request_processing_models= ["ClientServer", "ReactiveStreaming"]
