repetitions = 10
motor_groups_tcp = [4, 8, 16]
durations = [10, 30, 120]
window_size_seconds = [1, 3, 9]
sampling_interval_ms = [500, 1000, 2000]
thread_pool_sizes = [8, 40, 200]
request_processing_models= ["ClientServer", "ReactiveStreaming"]
