image: localhost/rsoc/clippy_rustfmt:latest
stages:
  - build
  - check
  - test

variables:
  SENSOR_ID: 0

cache:
  key:
    files:
      - Cargo.lock
  paths:
    - target/debug/deps
    - target/thumbv6m-none-eabi/debug/deps

build:
  stage: build
  tags:
    - rsoe
  script: "cargo build"
  artifacts:
    paths:
      - target/
    exclude:
      - target/debug/deps/**
      - target/thumbv6m-none-eabi/debug/deps/**

check-code-formatting:
  stage: check
  tags:
    - rsoe
  script: "cargo fmt --all -- --check"

lint:
  stage: check
  tags:
    - rsoe
  script: "cargo clippy --all-targets --all-features -- -D warnings"

test:
  stage: test
  tags:
    - rsoe
  script: "cargo test"