version: "3.9"
services:
  monitor:
    image: 127.0.0.1:5000/monitor
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
  cloud_server:
    image: 127.0.0.1:5000/cloud_server
    ports:
      - "8001:8001"
    deploy:
      replicas: 1
#      placement:
#        constraints:
#          - "node.role==manager"
  sensor:
    image: 127.0.0.1:5000/sensor
