version: "3.9"
services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile-motor-monitor
    ports:
      - "8000:8000"
  cloud_server:
    build:
      context: .
      dockerfile: Dockerfile-cloud-server
    ports:
      - "8001:8001"
  sensor:
    build:
      context: .
      dockerfile: Dockerfile-sensor
