version: "3.9"
services:
  monitor:
    image: ${REGISTRY_IP}:5000/monitor
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.platform.arch==aarch64"
  cloud_server:
    image: ${REGISTRY_IP}:5000/cloud_server
    ports:
      - target: 8001
        published: 8001
        mode: host
    deploy:
      replicas: 1
  sensor:
    image: ${REGISTRY_IP}:5000/sensor