[package]
name = "cloud_server"
version = "0.1.0"
edition = "2021"

[dependencies]
data_transfer_objects = { path = "../data_transfer_objects" }
utils = { path = "../utils" }
postcard = "1.0.2"
serde = { version = "1.0", default-features = false }
toml = "0.5.9"
env_logger = "0.10.0"
log = "0.4"