[package]
name = "motor_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
data_transfer_objects = { path = "../data_transfer_objects" }
postcard = { version = "1.0.0", features = ["alloc"] }
serde_json = "1.0.85"
threadpool = "1.8.1"
libc = { version = "0.2", default-features = false }