[test_run]
start_delay = 5

[motor_monitor]
window_size_seconds = 3
sensor_port = 9000
sampling_interval = 1000
thread_pool_size = 40

[motor_driver]
test_driver_port = 8000
sensor_driver_port = 11000

[cloud_server]
test_driver_port = 8001
motor_monitor_port = 10000

[validator]
validation_window = 3