[test_run]
start_delay = 1
duration = 30

[motor_monitor]
window_size_seconds = 3
sensors_start_port = 9000

[motor_driver]
test_driver_port = 8000
sensor_driver_port = 11000

[cloud_server]
test_driver_port = 8001
motor_monitor_port = 10000
