[test_run]
start_delay = 15

[motor_monitor]
sensor_listen_address = "127.0.0.1:9000"

[motor_driver]
test_driver_listen_address = "127.0.0.1:8000"
sensor_socket_addresses = ["127.0.0.1:11000", "127.0.0.1:11001", "127.0.0.1:11002", "127.0.0.1:11003"]

[cloud_server]
test_driver_listen_address = "127.0.0.1:8001"
motor_monitor_listen_address = "127.0.0.1:10000"